[package]
name = "rust-backend"
version = "0.1.0"
authors = ["David Raifaizen <d-raif@hotmail.com>"]

[dependencies]
iron = "0.4.0"
router = "0.3.4" # for iron

serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"